#!/bin/sh

export TF_VAR_lambda_role_arn=xxxxxxxxxxxxxxxxxxxx
export TF_VAR_twitter_api_key=xxxxxxxxxxxxxxxxxxxx
export TF_VAR_twitter_api_secret_key=xxxxxxxxxxxxxxxxxxxx
export TF_VAR_twitter_bearer_token=xxxxxxxxxxxxxxxxxxxx
export TF_VAR_twitter_access_token=xxxxxxxxxxxxxxxxxxxx
export TF_VAR_twitter_access_token_secret=xxxxxxxxxxxxxxxxxxxx
