version: "3.8"
services:
  minio:
    image: "minio/minio:RELEASE.2022-08-25T07-17-05Z"
    container_name: minio
    ports:
      - "9000:9999"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadminuser
      MINIO_ROOT_PASSWORD: minioadminpassword

    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/export:/export
      - ./docker/minio/config:/root/.minio
      - ./docker/minio/policies:/policies
